### ISSUE TITLE
Automated Build

### ISSUE THREAD

**Issue by tbsexton** [usnistgov/cord19-cdcs-nist#2]
TODO

- Travis
- jenkins
- plain makefile?
- scons
- Meson

**Comment by pdessauw** [comment]
The naming convention seems good, it is modular enough to allow various dataset / versions for the cv-py repo. 

There is an internal Jenkins that we can use to build the releases. It should be possible to add a Jenkinsfile to this repo containing the building steps for the archive. The Jenkinsfile allows transparency for external people who might want to use or fork our repo within their own orgs.

Let us look into this and we'll get back to you!

**Comment by tbsexton** [comment]
@pdessauw I'm working on a version on dev that will use the xml schema directly to create the json/csv distributions at build time. Once that goes live, could you update the jenkinsfile? 

I may open a separate issue that deals with roping various python-interface build commands into the `taskipy` system...that way the jenkinsfile has less to deal with internally.

**Comment by pdessauw** [comment]
I'm working on automating the tagging process for the releases as you advised (using [poetry-dynamic-versioning](https://pypi.org/project/poetry-dynamic-versioning/)). 

Changing the processing to use the XML files instead of the JSON should not be too complicated to implement.

Let me know what are the new tasks and I will update the `Jenkinsfile` to make use of them.
